Feature/members
RoBorregos/roborregos-web pull request #129
Opened 2021-04-25 02:07 UTC by Osvaldoav

### What does this PR do?

- Add Values section to Members
- Add SearchBar to Members
- Refactor Members and MembersGrid js files

#### Related issues

#78

2021-04-25 04:42 UTC, AuroTB requested changes
Excellent work! I really liked your PR. Impeccable code.

## Some UI/UX comments

**Values**
- Make upper and bottom padding smaller in the "Values" title
- Make text smaller in large view in the values description, I recommend to use vh (because its vertical)
- Make it fit the page (large and small view)
- make images fit the container, in large view it looks weird when repeting it

![image](https://user-images.githubusercontent.com/25405578/115978987-ba7e4d80-a548-11eb-871b-a9906871cdd3.png)
![image](https://user-images.githubusercontent.com/25405578/115979715-16e36c00-a54d-11eb-8ec4-d96f670afcfc.png)
![image](https://user-images.githubusercontent.com/25405578/115979831-d0dad800-a54d-11eb-9202-69b5b63fbf2e.png)

**Search bar**
- Map "software development" with "programmer", I think people will search for that
- Bug in galaxy fold dimensions, small view
![image](https://user-images.githubusercontent.com/25405578/115979773-78a3d600-a54d-11eb-9af5-4442ab44a368.png)


**Join us button**
- Modify the button border color to #00FFFA
- Center in small view
![image](https://user-images.githubusercontent.com/25405578/115979436-8b1d1000-a54b-11eb-9ea0-71b48821fd5e.png)
![image](https://user-images.githubusercontent.com/25405578/115979652-bf450080-a54c-11eb-878a-25342180be71.png)

2021-04-25 04:42 UTC, AuroTB commented on src/components/Members/MembersGrid/MembersGrid.js
> +      document.removeEventListener('keydown', keyListener)
nice

2021-06-12 01:28 UTC, Osvaldoav commented
> * Map "software development" with "programmer", I think people will search for that

I'd recommend to address this in the members json file; adding a "programmer" tag for every "software development" tag instead of hardcoding the match in the search engine.

2021-06-12 01:29 UTC, Osvaldoav commented
All comments have been addressed. Please check this out @AuroTB  :)

2021-06-22 20:20 UTC, AuroTB approved these changes
LGTM

2021-06-22 20:20 UTC, merged