Feature/horizontal timeline v2
RoBorregos/roborregos-web pull request #131
Opened 2021-05-09 22:25 UTC by zJuarez

### What does this PR do?

- new horizontal timeline implementation (responisve -> 3 elements on large, 2 on medium)
- on mobile devices still previous vertical timeline
- added common hook useWindowSize

** waiting on colors and general design approval**

#### Related issues

#118
![image](https://user-images.githubusercontent.com/44931871/116847558-61e62a80-abb0-11eb-9777-2568668223d5.png)
![image](https://user-images.githubusercontent.com/44931871/116847577-6dd1ec80-abb0-11eb-9054-06f022a3a367.png)

![image](https://user-images.githubusercontent.com/44931871/116847304-e84e3c80-abaf-11eb-9cff-2cb53259a632.png)
![image](https://user-images.githubusercontent.com/44931871/116847643-8e9a4200-abb0-11eb-9a1b-e3414a62ce20.png)

#### Merge Checklist:

- [ ] The branch is up-to-date (i.e. rebased) with the base branch
- [ ] No code style issues (eslint and flow)

2021-05-09 23:36 UTC, AuroTB commented on .gitignore
> +package-lock.json
thanks!

2021-05-10 00:09 UTC, AuroTB requested changes
Responsivity in this component is extremely well done!
I pointed some UI stuff (colors to #FF7549, in small and large view), but other than that the code looks clean and nice.

![image](https://user-images.githubusercontent.com/25405578/117591423-0826b880-b0fa-11eb-84da-d83a3f005d15.png)
(Change to orange)

2021-05-10 00:09 UTC, AuroTB commented on src/data/timeline.json
> +  "years" : [2015, 2016, 2017,2018,2019,2020],
nice!

2021-05-10 00:09 UTC, AuroTB commented on src/hooks/useWindowSize.js
> +    width: isSSR ? 1200 : window.innerWidth,
this is very nice

2021-05-10 00:09 UTC, AuroTB commented on src/components/About/AboutTimeline/AboutTimeline.js
> +              Our Story
you can add responsivity for thsi title too, looks very smile in [some very large views](https://github.com/RoBorregos/roborregos-web/wiki/Testing#responsivity)

![image](https://user-images.githubusercontent.com/25405578/117591267-56878780-b0f9-11eb-8ae6-98d1bc5a8d48.png)

2021-05-10 05:09 UTC, zJuarez commented on src/components/About/About.js
> +      <AboutTimeline events={timelineData.events} years={timelineData.years} />
import?

2021-05-10 20:16 UTC, AuroTB approved these changes
LGTM Great job!

2021-05-10 23:36 UTC, merged