Added 2023 members
RoBorregos/roborregos-web pull request #188
Opened 2024-11-27 02:54 UTC by GilMM27

2024-11-27 03:02 UTC, IvanRomero03 commented on src/data/members.json
> +        },
...

2024-11-27 04:36 UTC, Oscar-gg requested changes

2024-11-27 04:36 UTC, Oscar-gg commented on src/data/members.json
> +            "semesters": "8",
Fix semesters

2024-11-28 17:47 UTC, IvanRomero03 commented
ping on this pr, @GilMM27 hows the update going?

2024-11-28 19:43 UTC, IvanRomero03 approved these changes
lgtm if no more members to be added

2024-11-29 16:22 UTC, Oscar-gg commented
I think the following are pending:
- Fix image dimensions (Amin Image)
- Move inactive members to inactive section

2024-12-02 01:44 UTC, Oscar-gg approved these changes

2024-12-02 01:44 UTC, Oscar-gg commented
Lgtm 🚀

2024-12-02 15:35 UTC, merged