Changed the order of the tabs in the navbar, fixed logo ratio, and ad…
RoBorregos/roborregos-web pull request #91
Opened 2021-01-24 22:44 UTC by JFPach98

### What does this PR do?

- Changed the order of the tabs in the navbar, fixed logo ratio, and added sponsor to navbar.

#### Related issues

#

#### Merge Checklist:

- [ ] The branch is up-to-date (i.e. rebased) with the base branch
- [ ] No code style issues

2021-01-24 23:07 UTC, AuroTB requested changes
I've added a new image called _steren2.png_ to the sponsor's folder, so you can use it for the logo.
Also, please fix the responsive view.
![image](https://user-images.githubusercontent.com/25405578/105646652-a2723180-5e66-11eb-93d8-a75857bfcea6.png)

2021-01-25 00:04 UTC, JFPach98 commented
> I've added a new image called _steren2.png_ to the sponsor's folder, so you can use it for the logo.
In which branch?

2021-02-01 05:11 UTC, AuroTB requested changes
Looks nice! I've just added some comments.

2021-02-01 05:11 UTC, AuroTB commented on src/components/NavBar/NavBar.css
> +@media all and (max-width: 991px){
#navbar-legend-div1 has almost the same styling as #navbar-legend-div, why don't you try using the same styling for both of them? and instead, use `@media all and (min-width)` to change position and right.

2021-02-01 05:11 UTC, AuroTB commented on src/components/NavBar/NavBar.js
> +        <Navbar.Brand id="navbar-legend-div1">
Nice!

2021-02-04 06:38 UTC, AuroTB approved these changes
Everything looks great! Good job.
Before merging please resolve all comments and you are good to go!

2021-02-04 23:29 UTC, merged